name: python 3.8
on: [push]
jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Linting code
      run: |
        make lint
    - name: Test code with pytest
      run: |
        make test
    - name: Format code with python black
      run: |
         make format
